
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sat Mar 26 12:44:34 CET 2022
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int MULT = 40;
  public static final int CORCHETE_CERRADO = 24;
  public static final int DIFERENTE = 38;
  public static final int PORCENTAJE = 55;
  public static final int INT = 16;
  public static final int PUNTOCOMA = 7;
  public static final int ARRAY = 20;
  public static final int PAR_CERRADO = 11;
  public static final int SEPARADOR = 6;
  public static final int DELETE = 53;
  public static final int WRITE = 51;
  public static final int LLAVE_ABIERTA = 14;
  public static final int IDENTIFICADOR = 9;
  public static final int NOT = 28;
  public static final int AND = 32;
  public static final int IGUAL = 39;
  public static final int RECORD = 21;
  public static final int TYPE = 4;
  public static final int OR = 33;
  public static final int BOOL = 18;
  public static final int CALL = 54;
  public static final int DIV = 41;
  public static final int IF = 43;
  public static final int AMPERSAND = 13;
  public static final int ENDWHILE = 47;
  public static final int OF = 3;
  public static final int CORCHETE_ABIERTO = 23;
  public static final int EOF = 0;
  public static final int BOOLEAN = 31;
  public static final int NEW = 52;
  public static final int error = 1;
  public static final int COMA = 12;
  public static final int CADENA = 58;
  public static final int MENOS = 27;
  public static final int NULL = 42;
  public static final int MENOR = 34;
  public static final int PAR_ABIERTO = 10;
  public static final int ASIGNACION = 25;
  public static final int MAYOR = 35;
  public static final int REAL = 17;
  public static final int NUM_ENT = 29;
  public static final int FLECHA = 57;
  public static final int ENDIF = 46;
  public static final int ELSE = 44;
  public static final int NUM_REAL = 30;
  public static final int PUNTO = 56;
  public static final int READ = 50;
  public static final int NL = 2;
  public static final int WHILE = 45;
  public static final int MAYOR_IGUAL = 37;
  public static final int THEN = 49;
  public static final int PROC = 5;
  public static final int STRING = 19;
  public static final int LLAVE_CERRADA = 15;
  public static final int MENOR_IGUAL = 36;
  public static final int POINTER = 22;
  public static final int VAR = 8;
  public static final int DO = 48;
  public static final int MAS = 26;
}

