
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sat May 07 17:11:58 CEST 2022
//----------------------------------------------------

package c_ast;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int MULT = 36;
  public static final int CORCHETE_CERRADO = 23;
  public static final int DIFERENTE = 34;
  public static final int PORCENTAJE = 51;
  public static final int INT = 15;
  public static final int PUNTOCOMA = 7;
  public static final int ARRAY = 19;
  public static final int PAR_CERRADO = 10;
  public static final int SEPARADOR = 6;
  public static final int DELETE = 49;
  public static final int WRITE = 47;
  public static final int LLAVE_ABIERTA = 13;
  public static final int IDENTIFICADOR = 55;
  public static final int NOT = 27;
  public static final int AND = 28;
  public static final int IGUAL = 35;
  public static final int RECORD = 20;
  public static final int TYPE = 4;
  public static final int OR = 29;
  public static final int BOOL = 17;
  public static final int CALL = 50;
  public static final int DIV = 37;
  public static final int IF = 39;
  public static final int AMPERSAND = 12;
  public static final int ENDWHILE = 43;
  public static final int OF = 3;
  public static final int BOOLEAN = 54;
  public static final int CORCHETE_ABIERTO = 22;
  public static final int EOF = 0;
  public static final int NEW = 48;
  public static final int error = 1;
  public static final int COMA = 11;
  public static final int CADENA = 58;
  public static final int MENOS = 26;
  public static final int NULL = 38;
  public static final int MENOR = 30;
  public static final int PAR_ABIERTO = 9;
  public static final int ASIGNACION = 24;
  public static final int NUM_ENT = 56;
  public static final int REAL = 16;
  public static final int MAYOR = 31;
  public static final int FLECHA = 53;
  public static final int ENDIF = 42;
  public static final int NUM_REAL = 57;
  public static final int ELSE = 40;
  public static final int PUNTO = 52;
  public static final int READ = 46;
  public static final int NL = 2;
  public static final int WHILE = 41;
  public static final int MAYOR_IGUAL = 33;
  public static final int THEN = 45;
  public static final int PROC = 5;
  public static final int STRING = 18;
  public static final int LLAVE_CERRADA = 14;
  public static final int MENOR_IGUAL = 32;
  public static final int POINTER = 21;
  public static final int VAR = 8;
  public static final int DO = 44;
  public static final int MAS = 25;
}

