package alex;

public enum ClaseLexica {
 IDENTIFICADOR, SEPARADOR, INT, REAL, BOOL, NUM_ENT,NUM_REAL, BOOLEAN,
 ASIGNACION, PUNTOCOMA, PARABIERTO, PARCERRADO, 
 SUMA, RESTA, DIV, MULT, 
 AND, OR, NOT,
 MAYOR, MENOR , MAYORIGUAL, MENORIGUAL, IGUAL, DIFERENTE,
 EOF
}
