package alex;

public enum ClaseLexica {
	NUMENTERO, ID, NUMREAL, BOOLEAN, CADENA, SEPARADOR, INT, REAL, BOOL, ASIG, PUNTOCOMA, PARABIERTA, PARCERRADA, SUMA, RESTA,
	DIV, MULT, AND, OR, NOT, MAYOR, MENOR, MAYORIGUAL, MENORIGUAL, IGUAL, DIFERENTE, PORCENTAJE, CORCHETEABIERTO,
	CORCHETEABIERTO, LLAVEABIERTO, LLAVECERRADA, PUNTO, FLECHA, COMA, AMPERSAND, STRING, NULL, PROC, IF, THEN, ELSE,
	ENDIF, WHILE, DO, ENDWHILE, CALL, RECORD, ARRAY, OF, POINTER, NEW, DELETE, READ, WRITE, NL, VAR, TYPE
}
